Error
java.io.IOException: content://downloads/all_downloads/2191
	at l.۠۫ۙ.ۚۥ(S16K:213)
	at l.ۨۥۙ.ۢۥ(W17G:358)
	at l.ۚۚۗ.۠(6B3T:78)
	at l.ۚۚۗ.۠(Native Method)
	at l.ۦ۟ۗ.call(HB37:406)
	at java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1100)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:1572)
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/2191 from pid=13583, uid=10162 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2029)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1520)
	at l.۠۫ۙ.ۚۥ(S16K:211)
	... 8 more
